//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge.Valkimia.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challenge.Valkimia.Infrastructure.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cliente.
        /// </summary>
        public static string Buttons_CreateCliente {
            get {
                return ResourceManager.GetString("Buttons_CreateCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string Buttons_Details {
            get {
                return ResourceManager.GetString("Buttons_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado.
        /// </summary>
        public static string Common_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Common_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los derechos reservados por Stefano Zucarelli.
        /// </summary>
        public static string Labels_Copyright {
            get {
                return ResourceManager.GetString("Labels_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshabilitado.
        /// </summary>
        public static string Labels_Disabled {
            get {
                return ResourceManager.GetString("Labels_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Labels_Email {
            get {
                return ResourceManager.GetString("Labels_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        public static string Labels_Enabled {
            get {
                return ResourceManager.GetString("Labels_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera Página.
        /// </summary>
        public static string Labels_FirstPage {
            get {
                return ResourceManager.GetString("Labels_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Challenge Valkimia.
        /// </summary>
        public static string Labels_Home {
            get {
                return ResourceManager.GetString("Labels_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima Página.
        /// </summary>
        public static string Labels_LastPage {
            get {
                return ResourceManager.GetString("Labels_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string Labels_Loading {
            get {
                return ResourceManager.GetString("Labels_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Labels_Login {
            get {
                return ResourceManager.GetString("Labels_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string Labels_Logout {
            get {
                return ResourceManager.GetString("Labels_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Siguiente.
        /// </summary>
        public static string Labels_NextPage {
            get {
                return ResourceManager.GetString("Labels_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron resultados.
        /// </summary>
        public static string Labels_NoResults {
            get {
                return ResourceManager.GetString("Labels_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string Labels_Of {
            get {
                return ResourceManager.GetString("Labels_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Labels_Password {
            get {
                return ResourceManager.GetString("Labels_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Anterior.
        /// </summary>
        public static string Labels_PreviousPage {
            get {
                return ResourceManager.GetString("Labels_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando....
        /// </summary>
        public static string Labels_Processing {
            get {
                return ResourceManager.GetString("Labels_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Labels_Profile {
            get {
                return ResourceManager.GetString("Labels_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Labels_Search {
            get {
                return ResourceManager.GetString("Labels_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola.
        /// </summary>
        public static string Labels_Welcome {
            get {
                return ResourceManager.GetString("Labels_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Notifications_Error {
            get {
                return ResourceManager.GetString("Notifications_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exito.
        /// </summary>
        public static string Notifications_Success {
            get {
                return ResourceManager.GetString("Notifications_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        public static string Notifications_Warning {
            get {
                return ResourceManager.GetString("Notifications_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Titles_Clientes {
            get {
                return ResourceManager.GetString("Titles_Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Titles_Login {
            get {
                return ResourceManager.GetString("Titles_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo requerido.
        /// </summary>
        public static string Validations_Required {
            get {
                return ResourceManager.GetString("Validations_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe usar una contraseña diferente.
        /// </summary>
        public static string Validations_UseDifferentPassword {
            get {
                return ResourceManager.GetString("Validations_UseDifferentPassword", resourceCulture);
            }
        }
    }
}
